export const FETCH_PLAYLIST_RANDOM = "FETCH_PLAYLIST_RANDOM";

export const FETCH_TOP_NEWS = 'FETCH_TOP_NEWS';
export const FETCH_FAV_NEWS = 'FETCH_FAV_NEWS';

export const FETCH_RANDOM_PICS = 'FETCH_RANDOM_PICS';

export const SEARCH_MOVIE = 'SEARCH_MOVIE';


